/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl2;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TrustworthyStandaloneSetup extends TrustworthyStandaloneSetupGenerated {

	public static void doSetup() {
		new TrustworthyStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
