grammar org.xtext.example.mydsl2.Trustworthy with org.eclipse.xtext.common.Terminals

generate trustworthy "http://www.xtext.org/example/mydsl2/Trustworthy"

Model:
	'Setup:' rooms+=Room
	'Actions:' action=Action
	
;

Action:
	text+=ID ("," next=Action)? 
;
	
Room:
	'Room' name=ID  'with' sensors+=Sensor*
;

Sensor:
	amount=INT 'sensor' 'and' preset=ID 'preset' 'ssID:'ssID=ID ',' 'pass:'passwd=ID
;
