/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl2.trustworthy;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl2.trustworthy.Model#getRooms <em>Rooms</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl2.trustworthy.TrustworthyPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Rooms</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl2.trustworthy.Room}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rooms</em>' containment reference list.
   * @see org.xtext.example.mydsl2.trustworthy.TrustworthyPackage#getModel_Rooms()
   * @model containment="true"
   * @generated
   */
  EList<Room> getRooms();

} // Model
