/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl2.trustworthy;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sensor Part</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl2.trustworthy.SensorPart#getSensors <em>Sensors</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl2.trustworthy.TrustworthyPackage#getSensorPart()
 * @model
 * @generated
 */
public interface SensorPart extends Room
{
  /**
   * Returns the value of the '<em><b>Sensors</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl2.trustworthy.Sensor}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sensors</em>' containment reference list.
   * @see org.xtext.example.mydsl2.trustworthy.TrustworthyPackage#getSensorPart_Sensors()
   * @model containment="true"
   * @generated
   */
  EList<Sensor> getSensors();

} // SensorPart
