/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl2.trustworthy;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl2.trustworthy.TrustworthyFactory
 * @model kind="package"
 * @generated
 */
public interface TrustworthyPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "trustworthy";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl2/Trustworthy";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "trustworthy";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TrustworthyPackage eINSTANCE = org.xtext.example.mydsl2.trustworthy.impl.TrustworthyPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl2.trustworthy.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl2.trustworthy.impl.ModelImpl
   * @see org.xtext.example.mydsl2.trustworthy.impl.TrustworthyPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Rooms</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ROOMS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl2.trustworthy.impl.RoomImpl <em>Room</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl2.trustworthy.impl.RoomImpl
   * @see org.xtext.example.mydsl2.trustworthy.impl.TrustworthyPackageImpl#getRoom()
   * @generated
   */
  int ROOM = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__NAME = 0;

  /**
   * The number of structural features of the '<em>Room</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl2.trustworthy.impl.SensorImpl <em>Sensor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl2.trustworthy.impl.SensorImpl
   * @see org.xtext.example.mydsl2.trustworthy.impl.TrustworthyPackageImpl#getSensor()
   * @generated
   */
  int SENSOR = 2;

  /**
   * The feature id for the '<em><b>Amount</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__AMOUNT = 0;

  /**
   * The feature id for the '<em><b>Preset</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__PRESET = 1;

  /**
   * The number of structural features of the '<em>Sensor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl2.trustworthy.impl.SensorPartImpl <em>Sensor Part</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl2.trustworthy.impl.SensorPartImpl
   * @see org.xtext.example.mydsl2.trustworthy.impl.TrustworthyPackageImpl#getSensorPart()
   * @generated
   */
  int SENSOR_PART = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_PART__NAME = ROOM__NAME;

  /**
   * The feature id for the '<em><b>Sensors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_PART__SENSORS = ROOM_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Sensor Part</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_PART_FEATURE_COUNT = ROOM_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl2.trustworthy.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl2.trustworthy.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl2.trustworthy.Model#getRooms <em>Rooms</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rooms</em>'.
   * @see org.xtext.example.mydsl2.trustworthy.Model#getRooms()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Rooms();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl2.trustworthy.Room <em>Room</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Room</em>'.
   * @see org.xtext.example.mydsl2.trustworthy.Room
   * @generated
   */
  EClass getRoom();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl2.trustworthy.Room#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl2.trustworthy.Room#getName()
   * @see #getRoom()
   * @generated
   */
  EAttribute getRoom_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl2.trustworthy.Sensor <em>Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sensor</em>'.
   * @see org.xtext.example.mydsl2.trustworthy.Sensor
   * @generated
   */
  EClass getSensor();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl2.trustworthy.Sensor#getAmount <em>Amount</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Amount</em>'.
   * @see org.xtext.example.mydsl2.trustworthy.Sensor#getAmount()
   * @see #getSensor()
   * @generated
   */
  EAttribute getSensor_Amount();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl2.trustworthy.Sensor#getPreset <em>Preset</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Preset</em>'.
   * @see org.xtext.example.mydsl2.trustworthy.Sensor#getPreset()
   * @see #getSensor()
   * @generated
   */
  EAttribute getSensor_Preset();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl2.trustworthy.SensorPart <em>Sensor Part</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sensor Part</em>'.
   * @see org.xtext.example.mydsl2.trustworthy.SensorPart
   * @generated
   */
  EClass getSensorPart();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl2.trustworthy.SensorPart#getSensors <em>Sensors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sensors</em>'.
   * @see org.xtext.example.mydsl2.trustworthy.SensorPart#getSensors()
   * @see #getSensorPart()
   * @generated
   */
  EReference getSensorPart_Sensors();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TrustworthyFactory getTrustworthyFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl2.trustworthy.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl2.trustworthy.impl.ModelImpl
     * @see org.xtext.example.mydsl2.trustworthy.impl.TrustworthyPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Rooms</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ROOMS = eINSTANCE.getModel_Rooms();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl2.trustworthy.impl.RoomImpl <em>Room</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl2.trustworthy.impl.RoomImpl
     * @see org.xtext.example.mydsl2.trustworthy.impl.TrustworthyPackageImpl#getRoom()
     * @generated
     */
    EClass ROOM = eINSTANCE.getRoom();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROOM__NAME = eINSTANCE.getRoom_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl2.trustworthy.impl.SensorImpl <em>Sensor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl2.trustworthy.impl.SensorImpl
     * @see org.xtext.example.mydsl2.trustworthy.impl.TrustworthyPackageImpl#getSensor()
     * @generated
     */
    EClass SENSOR = eINSTANCE.getSensor();

    /**
     * The meta object literal for the '<em><b>Amount</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENSOR__AMOUNT = eINSTANCE.getSensor_Amount();

    /**
     * The meta object literal for the '<em><b>Preset</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENSOR__PRESET = eINSTANCE.getSensor_Preset();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl2.trustworthy.impl.SensorPartImpl <em>Sensor Part</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl2.trustworthy.impl.SensorPartImpl
     * @see org.xtext.example.mydsl2.trustworthy.impl.TrustworthyPackageImpl#getSensorPart()
     * @generated
     */
    EClass SENSOR_PART = eINSTANCE.getSensorPart();

    /**
     * The meta object literal for the '<em><b>Sensors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR_PART__SENSORS = eINSTANCE.getSensorPart_Sensors();

  }

} //TrustworthyPackage
