/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl2.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTrustworthyScopeProvider extends DelegatingScopeProvider {
}
